= TADL Specification
:source-highlighter: highlight.js
:highlightjs-languages: asciidoc, abnf
:toc:
Torben Schinke

== Workspace
A workspace defines the root of the modelling domain, including all subdomains and bounded contexts. These definitions
provide the central aspects for all domain solutions. The according requirements' (problem space) and specifications
(solution space) are usually defined inside modules. A workspace is created by declaring a *tadl.workspace*
file which itself annotates declared identifiers as contexts. Nested workspace files are not allowed and therefore
not interpreted as a workspace file. Each declared QualifiedLowCaseIdentifier must be declared exactly once. Each
declared QualifiedLowCaseIdentifier must be defined exactly once in a glossary.

Grammar:
[source,abnf]
----
; tadl.workspace
ContextDefinition           =   "context" QualifiedIdentifier
QualifiedLowCaseIdentifier  =   QualifiedLowCaseIdentifier ("." QualifiedLowCaseIdentifier)*
LowCaseIdentifier           =   `([a-z][a-z0-9_]*)`
----

Example:
[source,tadl]
----
// tadl.workspace
context yasa.support.ticket

context yasa.support.file

context yasa.support.iam
----

== Module
Any specification or solution must be declared within a module. A module is declared using a *tadl.mod* file
and describes generator specific configurations. These settings configure how the language neutral specification
must be rendered. A module is accompanied by a *tadl.mod.adoc* file, which describes the rough visions and goals which
this specification shall solve. It must not be empty and allows a subset of AsciiDoc.

Currently, only a Go generator is specified.

=== Go
Grammar:
[source,abnf]
----
; tadl.mod
ModuleDefinition           =   "module" Identifier
GoDefinition            = "go" { "module" = string "output" = string }
Identifier           =   `([a-zA-Z_][a-zA-Z0-9_]*)`
----


Example:
[source,tadl]
----
module OlzerpService {

    go {
        module = "github.com/worldiety/supportiety"
        output = "{{env `WORKSPACE_DIR`}}/supportiety/service"

        // import defines standard library imports, however may be external anyway, cannot control that.
        // The identifiers must be unique for the entire module.
        import {
            # ...provides access to atomic primitives.
            sync "sync"
        }

        // require defines external dependencies
        require {
            # ...provides CLDR stuff which is not present in the standard library.
            "golang.org/x/text" @ "v0.3.0" import {
                    mytext "golang.org/x/text"
                    otherpkg "golang.org/x/text/subpackage"
            }
        }
    }
}
----

== Glossary
Each bounded context has its own language. A project is usually made up different bounded contexts, possibly using
overloaded concept identifiers. Thus, a glossary per context is required. Glossary items are parsed from files,
named *glossary.adoc* which can be placed anywhere and multiple times within a context. If a single glossary
is to big, split it up and place it near their most important usage of the specification.
The required definition is a subset of the AsciiDoc markup language. A cross reference can be inserted using the
identifier of the definition. The identifier has to be unique across the entire workspace. Use a context
prefix for the id, to make it unique.

Grammar:
[source,abnf]
----
; glossary.adoc
glossary    =   header definition*
header      =   "[glossary]" "\n"
definition  =   "[[" identifier "]]" name "::" text "\n"
identifier  =   `([a-zA-Z_][a-zA-Z0-9_]*)`
name, text  =   `all chars but ::`
----

Example:
[source,asciidoc]
----
// glossary.adoc
[glossary]

[[yasa]]YASA::
YASA is a company creating extraordinary software products for their customers.

[[yasa-support-olzerp]]OLZERP::
...denotes the product of the support software within <<yasa>>.
----


== Requirements and specifications
There is an entire industry about requirements engineering, and we cannot cover this topic exhaustively here.
The specification defined in TADL is not suited to replace the
https://www.omg.org/spec/ReqIF/About-ReqIF/[Requirements Interchange Format (ReqIF)], however it probably
covers more than a simple Excel sheet or Word document. Describing requirements and specifications in a structured
format is an essential part of professional software development and liability, as required by ISO 29148, IEEE 1233 or
ISO 12207.

[NOTE.definition,caption=Definition]
====
A requirement describes what a customer or user expects from a software product.
It contains functional or non-functional conditions, goals and primarily benefits. Requirements are the _wishlist_
of your customer. A requirement is more about a vision and not a technical solution and are aggregated
in a product requirements document (_Lastenheft_) and shall be created by the customer. It describes the problem space.
====

[NOTE.definition,caption=Definition]
====
A specification  All specifications shall be created by the contractor and are aggregated in a scope statement or
technical concept (_Pflichtenheft_).
by
====

An admonition draws attention to auxiliary information.

A requirement is a specification or documentation of goals or expectations from actors in the real world. Depending on
the project and context, parts of a requirement must be machine-readable. However, there is no reason to force a markup,
if no such need arises. Requirements are written in text form and can be placed everywhere in the workspace. However,
each requirement must have a unique ID in the entire domain. We encourage putting requirements where they fit best
and nearest to the place of their use, e.g. within a projects' context folder.

A requirement file is essentially an AsciiDoc file, however only a subset is supported.

[source,asciidoc]
----

// level 1 section title must be a unique identifier for the requirement.
== DownloadWorkspace 

// the arbitrary text body of a section describes the requirement. It must not be empty. Recommended is 
// a user story format, e.g. as proposed by Mike Cohen (As a < type of user >, I want < some goal > so that 
// < some reason >), but the format is not validated. The natural language of stories depends on the actual project, 
// but in non-international projects this is not necessarily english and sometimes even can't be translated, like 
// specialised vocabulary in government agencies.
Als Entwickler möchte ich einen Workspace herunterladen können, um ihn reparieren zu können.

// level 2 section title must be a unique identifier in scope for a scenario or acceptance criteria.
// In this example, its address is DownloadWorkspace#LargeFiles.
=== LargeFiles

Als Entwickler kann ich auch Dateien herunterladen, die größer sind als 4GiB.

=== ManyFiles

Kunden können beliebig viele Dateien hochladen.

===

----
