// Code generated by go generate; DO NOT EDIT.
package token

const (
	TokenCharData        Type = "TokenCharData"
	TokenIdentifier      Type = "TokenIdentifier"
	TokenBlockStart      Type = "TokenBlockStart"
	TokenBlockEnd        Type = "TokenBlockEnd"
	TokenGroupStart      Type = "TokenGroupStart"
	TokenGroupEnd        Type = "TokenGroupEnd"
	TokenGenericStart    Type = "TokenGenericStart"
	TokenGenericEnd      Type = "TokenGenericEnd"
	TokenG2Preamble      Type = "TokenG2Preamble"
	TokenDefineElement   Type = "TokenDefineElement"
	TokenDefineAttribute Type = "TokenDefineAttribute"
	TokenAssign          Type = "TokenAssign"
	TokenG1LineEnd       Type = "TokenG1LineEnd"
	TokenComma           Type = "TokenComma"
	TokenSemicolon       Type = "TokenSemicolon"
	TokenG1Comment       Type = "TokenG1Comment"
	TokenG2Comment       Type = "TokenG2Comment"
	TokenG2Arrow         Type = "TokenG2Arrow"
)

func (t *CharData) Type() Type {
	return TokenCharData
}

func (t *CharData) Pos() *Position {
	return &t.Position
}

func (t *Identifier) Type() Type {
	return TokenIdentifier
}

func (t *Identifier) Pos() *Position {
	return &t.Position
}

func (t *BlockStart) Type() Type {
	return TokenBlockStart
}

func (t *BlockStart) Pos() *Position {
	return &t.Position
}

func (t *BlockEnd) Type() Type {
	return TokenBlockEnd
}

func (t *BlockEnd) Pos() *Position {
	return &t.Position
}

func (t *GroupStart) Type() Type {
	return TokenGroupStart
}

func (t *GroupStart) Pos() *Position {
	return &t.Position
}

func (t *GroupEnd) Type() Type {
	return TokenGroupEnd
}

func (t *GroupEnd) Pos() *Position {
	return &t.Position
}

func (t *GenericStart) Type() Type {
	return TokenGenericStart
}

func (t *GenericStart) Pos() *Position {
	return &t.Position
}

func (t *GenericEnd) Type() Type {
	return TokenGenericEnd
}

func (t *GenericEnd) Pos() *Position {
	return &t.Position
}

func (t *G2Preamble) Type() Type {
	return TokenG2Preamble
}

func (t *G2Preamble) Pos() *Position {
	return &t.Position
}

func (t *DefineElement) Type() Type {
	return TokenDefineElement
}

func (t *DefineElement) Pos() *Position {
	return &t.Position
}

func (t *DefineAttribute) Type() Type {
	return TokenDefineAttribute
}

func (t *DefineAttribute) Pos() *Position {
	return &t.Position
}

func (t *Assign) Type() Type {
	return TokenAssign
}

func (t *Assign) Pos() *Position {
	return &t.Position
}

func (t *G1LineEnd) Type() Type {
	return TokenG1LineEnd
}

func (t *G1LineEnd) Pos() *Position {
	return &t.Position
}

func (t *Comma) Type() Type {
	return TokenComma
}

func (t *Comma) Pos() *Position {
	return &t.Position
}

func (t *Semicolon) Type() Type {
	return TokenSemicolon
}

func (t *Semicolon) Pos() *Position {
	return &t.Position
}

func (t *G1Comment) Type() Type {
	return TokenG1Comment
}

func (t *G1Comment) Pos() *Position {
	return &t.Position
}

func (t *G2Comment) Type() Type {
	return TokenG2Comment
}

func (t *G2Comment) Pos() *Position {
	return &t.Position
}

func (t *G2Arrow) Type() Type {
	return TokenG2Arrow
}

func (t *G2Arrow) Pos() *Position {
	return &t.Position
}
