// SPDX-FileCopyrightText: © 2021 The dyml authors <https://github.com/golangee/dyml/blob/main/AUTHORS>
// SPDX-License-Identifier: Apache-2.0

// Package parser contains the parser that transforms tokens generated by the lexer
// in package token to a tree representation.
package parser
